
commit;

-- 1번 문제---
SELECT PAT_NAME FROM PATIENT
WHERE PAT_GENDER = 'M'
AND PAT_NAME LIKE '오%'; -- 1번

SELECT PAT_NAME FROM PATIENT
WHERE PAT_GENDER = 'M'
AND PAT_NAME LIKE '오%'
AND PAT_BIRTH NOT LIKE '1979%'; -- 2번

SELECT PAT_NAME FROM PATIENT
WHERE PAT_BIRTH BETWEEN '19800000' AND '19899999'
AND PAT_GENDER = 'F'; -- 3번

SELECT PAT_NAME FROM PATIENT
WHERE PAT_NAME LIKE '__오성'
AND PAT_BIRTH LIKE '2004%'
AND PAT_GENDER = 'M';
--4. 환자이름이 4자이며 '오성'으로 끝나는 환자 중 생년월일이 2004년생 남자 환자만 조회
--남궁오성

SELECT PAT_NAME FROM PATIENT
WHERE  PAT_BIRTH LIKE '2000%'
AND PAT_GENDER = 'F'
AND PAT_NAME NOT LIKE '%환자';
--5. 2000년생 여자 중 이름 뒤 두글자가 '환자'로 끝나지 않는 환자조회
--28	한아름


SELECT PAT_NAME FROM PATIENT
WHERE PAT_NAME LIKE '____'
AND PAT_TEL IS NULL;
--6. 환자이름이 4자인사람 중에 휴대폰 번호가 등록되어있지 않은 환자조회
--4	오환자2
--7	오환자3
--45	황보희라


-- 2번 ----------
SELECT PAT_CODE, PAT_NAME
FROM PATIENT 
WHERE PAT_CODE IN(
SELECT PAT_CODE
FROM TREAT T
WHERE (TRT_YEAR=2012 AND TRT_DATE=0103)
AND DOC_CODE IN(
SELECT DOC_CODE FROM DOCTOR
WHERE DEP_CODE LIKE '05%' OR DEP_CODE LIKE '08%' OR DEP_CODE LIKE '13%'))
ORDER BY PAT_CODE;
    
--1. 2012년 1월 3일 내원환자 중 
-- 정형외과(코드:05xx)와 성형외과(코드:08xx)와 이비인후과(코드:13xx)
-- 환자조회
32	박환자
33	권이나
37	강성
42	지유
43	허민지

SELECT PAT_CODE, PAT_NAME
FROM PATIENT
WHERE PAT_CODE IN(
SELECT PAT_CODE 
FROM TREAT T
WHERE (TRT_YEAR = 2012 AND TRT_DATE=0103) 
AND (TRT_TIME BETWEEN 0900 AND 1200)
AND DOC_CODE NOT IN(SELECT DOC_CODE FROM DOCTOR
WHERE DEP_CODE LIKE '05%' OR DEP_CODE LIKE '08%' OR DEP_CODE LIKE '13%'))
ORDER BY PAT_CODE;

--2. 2012년 1월 3일 내원환자 중 내원 진료시간이 09:00 ~ 12:00 이고
-- 진료과가 정형외과(코드:05xx)와 성형외과(코드:08xx)와 이비인후과(코드:13xx)
-- 가 아닌 환자조회
30	권환자
35	황환자
39	고기리
40	유희애

SELECT T.PAT_CODE, P.PAT_NAME
FROM PATIENT P, TREAT T
WHERE P.PAT_CODE = T.PAT_CODE
AND (TRT_YEAR=2014 AND TRT_DATE=0101);
 
-- SELECT * FROM ( SELECT rownum rank, 
--TRT BETWEEN 
--ORDER BY TRT_TIME DESC;
--3. 2014년 1월 1일 내원환자 중 5명만 출력
-- (진료시간순서 상 마지막 진료환자 5명)

5	오대식
19	우별희
21	송주희
24	차은비
27	안성댁

SELECT PAT_CODE,PAT_NAME FROM  (
    SELECT rownum rnum, TMP.*FROM(
            SELECT T.PAT_CODE, P.PAT_NAME
            FROM PATIENT P, TREAT T
            WHERE P.PAT_CODE = T.PAT_CODE
            AND (TRT_YEAR=2014 AND TRT_DATE=0101)         
    )TMP
)R
WHERE rnum between 9 and 13;
--3번-------
SELECT DEP_NAME, DOC_NAME, TRT_RECEIPT, T.PAT_CODE, PAT_NAME, PAT_BIRTH, PAT_GENDER
FROM PATIENT P, TREAT T, DOCTOR D, DEPARTMENT DE
WHERE D.DEP_CODE = DE.DEP_CODE 
    AND  D.DOC_CODE = T.DOC_CODE
    AND  T.PAT_CODE = P.PAT_CODE
    AND (TRT_YEAR = 2013 AND TRT_DATE = 0125)
ORDER BY DEP_NAME, DOC_NAME, TRT_RECEIPT DESC; 

--1. 2013년 1월 25일 내원한 환자중 다음의 정보조회
-- 진료과명, 진료의사명, 접수시간, 환자번호, 환자이름, 생년월일, 성별
--(진료과, 진료의, 접수시간으로 내림차순 정렬)




SELECT TRT_DATE, T.PAT_CODE, PAT_NAME, PAT_BIRTH, PAT_GENDER, I.INP_DATE, I.INP_TIME
FROM PATIENT P, TREAT T, INPATIENT I
WHERE P.PAT_CODE = T.PAT_CODE
AND P.PAT_CODE = I.PAT_CODE(+)
AND (TRT_YEAR = 2013 AND TRT_DATE = 1225)
ORDER BY TRT_TIME;
--2. 2013년 12월 25일 내원한 환자의 다음 정보조회
--내원일자, 환자번호, 환자이름, 생년월일, 성별
--*단 2014년 이후로 입원했던적이 있다면 입원일자, 입원시간도 출력
--(진료시간 기준 정렬)
-- OUTER JOIN (+)
